# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version=47.4.20
forge_version_range=[47.1.30,)
loader_version_range=[47,)

# required
ldlib2_version=2.2.27

# optional
kubejs_version=2001.6.5-build.16
rhino_version=2001.2.3-build.10
sophisticated_backpacks_version=1.20.1-3.24.59.1960
sophisticated_core_version=1.20.1-1.3.60.2099
beyonddimensions_version=8340189
lightmans_currency_version=1.20.1-2.3.0.5
curios_version=5.14.1+1.20.1
# confluence_lib_version=0.0.5
# confluence_version=1.2.2-260208
terra_curio_version=0.2.0-modid_renamed
terra_entity_version=1.2.3
# magic_coins_version=7605721
# sg_economy_api_version=7604579
jech_version=8117466
tacz_version=1.1.8-hotfix
slashblade_resharped_version=1.9.65

# runtime
# iris_version=1.8.12+1.21.1-neoforge
sodium_version=0.3.31+mc1.20.1
lsp_version=4776657
jei_version=vnxhddW4
