modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
#clientSideOnly=true - defaults to false if absent
[[mods]]
modId="viscript_recipe"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.viscript_recipe]]
modId = "minecraft"
mandatory=true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "ldlib2"
mandatory=true
versionRange = "[${ldlib2_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "irons_spellbooks"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "iceandfire"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "farmersdelight"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "create"
mandatory=false
versionRange = "[6.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "ars_nouveau"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "kaleidoscope_cookery"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "avaritia"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "extendedcrafting"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "cataclysm"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "spore"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "goety"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.viscript_recipe]]
modId = "touhou_little_maid"
mandatory=false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[features.viscript_recipe]
openGLVersion = "[3.2,)"
